language: java

addons:
  sonarcloud:
    organization: "naumovap"
    token:
      secure: "587fbec2d9d054f776d20c1f77d8465ebd18b125" # encrypted value of your token


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=naumovap_HashTableWithSearchTree

